apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: kafka-consumer
  template:
    metadata:
      name: kafka-consumer
      labels:
        app: kafka-consumer
        deployment: kafka-consumer
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: kafka-consumer
        image: clamer/kafka-consumer:0.0.1
        # image: image-registry.openshift-image-registry.svc:5000/amqstreams-cicd/kafka-consumer:0.0.1
        resources:
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 1500m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
