apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: kafka-consumer
    app.kubernetes.io/component: kafka-consumer
    app.kubernetes.io/instance: kafka-consumer
  name: kafka-consumer
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kafka-consumer
