apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-target-consumer
    app.kubernetes.io/component: kafka-target-consumer
    app.kubernetes.io/instance: kafka-target-consumer
  name: kafka-target-consumer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deployment: kafka-target-consumer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
