apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-target-consumer
  name: kafka-target-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: kafka-target-consumer
  template:
    metadata:
      name: kafka-target-consumer
      labels:
        app: kafka-target-consumer
        deployment: kafka-target-consumer
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: kafka-target-consumer
        image: clamer/kafka-consumer:0.0.2
        resources:
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 1500m
            memory: 1Gi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: KAFKA_TOPIC
            value: my-cluster-source.messages
          - name: KAFKA_CONSUMER_GROUP
            value: messagesgroup
          - name: KAFKA_BOOTSTRAP_SVC
            value: my-target-kafka-bootstrap
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
