apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - developerteam1-stage
    - developerteam1-prod
    - developerteam2-stage
    - developerteam2-prod
    - bookinfo
