apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demoapp
  namespace: argocd
spec:
  description: Lab Cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
  - https://github.com/paolocarta/ocp-gitops-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Lab Cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
  - https://github.com/paolocarta/ocp-gitops-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: argocd
spec:
  description: Lab Operators
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
  - https://github.com/paolocarta/ocp-gitops-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
  namespace: argocd
spec:
  description: CI/CD
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
  - https://github.com/paolocarta/ocp-gitops-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amqstreams
  namespace: argocd
spec:
  destination:
    namespace: amqstreams
    server: 'https://kubernetes.default.svc'
  project: infra
  source:
    path: 5-applications/amqstreams
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipeline-devteam1
  namespace: argocd
spec:
  destination:
    namespace: developerteam1-cicd
    server: 'https://kubernetes.default.svc'
  project: cicd
  source:
    # chart: springboot-tekton
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: deploy.namespace.prefix
        value: developerteam1
    path: 5-applications/cicd/tekton-pipeline
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: codereadyworkspaces
#   namespace: argocd
# spec:
#   destination:
#     namespace: codereadyworkspaces
#     server: 'https://kubernetes.default.svc'
#   ignoreDifferences:
#   - group: org.eclipse.che
#     jsonPointers:
#     - /spec/auth/identityProviderClientId
#     - /spec/auth/identityProviderRealm
#     - /spec/auth/identityProviderImage
#     - /spec/auth/identityProviderURL
#     kind: CheCluster
#   project: infra
#   source:
#     path: 5-applications/codereadyworkspaces
#     repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
#     targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-operators
  namespace: argocd
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: operators
  source:
    path: 5-applications/operators
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-metering
  namespace: argocd
spec:
  destination:
    namespace: openshift-metering
    server: 'https://kubernetes.default.svc'
  project: infra
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: 5-applications/metering
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developertools
  namespace: argocd
spec:
  destination:
    namespace: developertools
    server: 'https://kubernetes.default.svc'
  project: infra
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: 5-applications/developertools
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
spec:
  destination:
    namespace: bookinfo
    server: 'https://kubernetes.default.svc'
  project: demoapp
  source:
    path: 5-applications/bookinfo
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-service-mesh
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: maistra.io
    jsonPointers:
    - /spec/members
    kind: ServiceMeshMemberRoll
  project: infra
  source:
    path: 5-applications/servicemesh
    repoURL: https://github.com/paolocarta/ocp-gitops-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
