apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  labels:
{{ include "springboot-tekton.labels" . | nindent 4 }}
  name: deploy
spec:
  workspaces:
    - name: output-area
  params:
    - description: The namespace we are tagging to
      name: toNamespace
      type: string
    - description: The image tag
      name: tag
      type: string
      default: latest
    - description: the deployment
      name: deployment-folder
      type: string
      default: manifests
  resources:
    inputs:
      - name: gitops-repo
        type: git
  steps:
  - name: yq-version-update
    image: clamer/kikd:1.0.2
    workingDir: /workspace/gitops-repo
    script: |
      yq write -i $(params.deployment-folder)/deployment.yml \
        "spec.template.spec.containers[0].image" \
        {{.Values.fullnameOverride}}:"$(cat /workspace/output-area/version)"

  # - name: git-commit-repo
  #   image: clamer/kikd:1.0.2
  #   workingDir: /workspace/gitops-repo
  #   command: ["/bin/bash"]
  #   args:
  #     - "-c"
  #     - "git commit -am 'update to version "$(cat /workspace/output-area/version)"'"

  # - name: git-push-repo
  #   image: clamer/kikd:1.0.2
  #   workingDir: /workspace/gitops-repo
  #   command: ["/bin/bash"]
  #   args:
  #     - "-c"
  #     - "git push origin master"