apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basic-spring-boot
  name: basic-spring-boot
  namespace: developerteam1-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: basic-spring-boot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: basic-spring-boot
        deployment: basic-spring-boot
      name: basic-spring-boot
    spec:
      containers:
      - name: basic-spring-boot
        image: image-registry.openshift-image-registry.svc:5000/developerteam1-cicd/basic-spring-boot:1.0.34
        resources:
          requests:
            cpu: 300m
            memory: 400Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -s 'http://localhost:8080/'
