apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    app: basic-spring-boot
  name: basic-spring-boot
  namespace: developerteam1-stage
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: basic-spring-boot
---
apiVersion: v1
id: basic-spring-boot-http
kind: Route
metadata:
  annotations:
    description: Route for application's http service.
  labels:
    app: basic-spring-boot
  name: basic-spring-boot
  namespace: developerteam1-stage
spec:
  to:
    kind: Service
    name: basic-spring-boot
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: basic-spring-boot
  name: basic-spring-boot
  namespace: developerteam1-stage