apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: kafka-producer
    app.kubernetes.io/component: kafka-producer
    app.kubernetes.io/instance: kafka-producer
  name: kafka-producer
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/kafka-producer
