# Default values for springboot-tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kafka-producer
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "kafka-producer"
fullnameOverride: "kafka-producer"

serviceAccount:
  name: pipeline-with-keys

imagestream:
  name: redhat-openjdk18-openshift:1.5
  namespace: openshift

deploy:
  namespace:
    prefix: amqstreams

git:
  source:
    repository: git@github.com:paolocarta/kafka-producer-spring-cloud-stream.git
    revision: master
  templates:
    repository: git@github.com:paolocarta/ocp-gitops-argocd.git
    revision: master

pvc:
  enabled: true
  size: 5Gi

maven:
  image:
    repository: maven
    tag: 3.6.3-openjdk-11-slim
    
sonar:
  enabled: false
  # url: http://ns3306290.ip-178-32-219.eu:9000