apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kafka-producer
    app.kubernetes.io/component: kafka-producer
    app.kubernetes.io/instance: kafka-producer
  name: kafka-producer
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: kafka-producer:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/paolocarta/kafka-producer-spring-cloud-stream.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11-rhel7:latest
        namespace: amqstreams
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: SEHR_yvmc6m7A-wcZLIp
    type: GitHub
  - generic:
      secret: 1URHo2Y11CBs3KmFzGs_
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: registry.access.redhat.com/openjdk/openjdk-11-rhel7@sha256:4dc1ae6af9a3efbbd28c1b765faa6fcea3f8eddccd2347ad97713d312f57b511
    type: ImageChange
status:
  lastVersion: 16
