apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kafka-consumer
    app.kubernetes.io/component: kafka-consumer
    app.kubernetes.io/instance: kafka-consumer
  name: kafka-consumer
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: kafka-consumer:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/paolocarta/kafka-consumer-spring-cloud-stream.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11-rhel7:latest
        namespace: amqstreams
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: B1P6d8CIq6j1KvzB_m8E
    type: GitHub
  - generic:
      secret: DiSQWiKxPbScjboQFlhy
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
