apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11-rhel7
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/openjdk/openjdk-11-rhel7
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
