apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: operator-metering
  namespace: openshift-metering
spec:
  storage:
    hive:
      type: "sharedPVC"
      sharedPVC:
        createPVC: true
        storageClass: "managed-nfs-storage"
        size: "5Gi"
    type: hive
  hive:
    spec:
      metastore:
        storage:
          class: "managed-nfs-storage"
          size: "5Gi"

